project_id = "zrhjykyualhbwjlpjckh"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600

[functions.create-deposit-session]
verify_jwt = true

[functions.create-deposit-session-eur]
verify_jwt = true

[functions.process-withdrawal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.test-payment-system]
verify_jwt = false

[functions.cleanup-old-abandons]
verify_jwt = false

[functions.sync-stripe-status]
verify_jwt = true

[functions.check-stripe-session]
verify_jwt = true