// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrhjykyualhbwjlpjckh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyaGp5a3l1YWxoYndqbHBqY2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTExODcsImV4cCI6MjA2OTYyNzE4N30.tH4tRyN-86bvk9CQnp32GLq6OO9LS7HCB5X48FRSkK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});